from random import randint
data = {
    "historia1": {
        "Oficina": "El genio y el maestro estaban en la oficina dormidos y se encontraron algunos vasos con alcohol",
        "Cocina": "En la cocina se encontro una pildora en el bote de basura en la parte de arriba",
        "Patio": "El jardinero estaba en el patio a la hora de lo ocurrido",
        "Cuarto de herramientas": "En el cuarto de herramientas se encontraba la esposa",
        "Dormitorio": "Se encontro la ropa interior de una mujer tirada cerca de la cama y una pistola en el buro a lado de la cama",
        "Pildora": "Se encontro una pildora rota en la basura de la cocina",
        "Pistola": "Se encontro una pistola en el dormitorio",
        "Cuchillo": "Se encontraron los cuchillos en la cocina",
        "Bat de beisbol": "El bat de beisbol se encontro en la oficina",
        "Machete": "El machete se encontro en el cuarto de herramientas",
        "Cocinera": "No se porque dudan de mi, yo le lleve el cafe al jefe a las 11:45pm ademas que yo lo amaba, ¡¡¡Jamas le haria eso!!!",
        "Maestro": "Yo no se que fue lo que ocurrio, estaba bebiendo con el y con el genio en la oficina y de repente me quede dormido, deberias preguntarle al genio",
        "Genio": "Yo no recuerdo que fue lo que sucedio, estaba en la cocina y de la nada me quede dormido y no se que paso",
        "Esposa": "Yo no pude ser yo estaba en el cuarto de herramientas y cuando me encamine a la oficina lo encontre muerto y posterior a eso lo llame",
        "Jardinero": "yo me encontraba en el patio acomodando las herramientas que utilice en la tarde",
        "ConclusionC": "La verdad fue que el genio mato al esposo en la oficina con una pildora porque quería todo el crédito del invento que estaban desarrollando",
        "ConclusionL": "A las 11:45 como estaba estipulado la cocinera le llevaría el café de la noche a su oficina donde el esposo se encontraba conversando con el genio acerca de un plan para cambiar el mundo, pero en eso llego el maestro y con una envidia profunda hacia el esposo puesto que el tenía todo lo que el quería los emborracho, el genio sabiendo de la envidia que sentía el maestro intuyo su plan de dejarlo en ridículo y le siguió la corriente, de repente observo que se estaban totalmente ebrios y el midiendo su bebida se hizo el borracho, el genio al ver que ninguno de los dos estaba consciente de lo que pasaba  y viendo las intenciones de la cocinera y al saber que la esposa estaba en el cuarto de herramientas y el jardinero estaba en el patio, ingreso una píldora a su bebida que lo dejaría muerto en tan solo 10 min, e inmediatamente en cuanto la cocinera se llevó al esposo él fue a la cocina y dejo la basura de la píldora con la intención de culparla, la cocinera lo llevo al dormitorio con la intención de tener un bebe con el esposo pero él no se dejó puesto que era homosexual, la cocinera no soporto tal rechazo y se fue llorando a la cocina, de repente regreso el esposo a la oficina donde se encontraban el genio y el maestro, la píldora hizo efecto a las 11:58, a las 12 la esposa se dirigió a la oficina y lo encontró muerto e inmediatamente llamo a todos los que estaban en esa casa y al detective",
        "Resultado_correcto" : ["Genio","Pildora","Oficina"]
        },
    "historia2": {
        "Oficina": "El genio y el maestro estaban en la oficina dormidos y se encontraron algunos vasos con alcohol",
        "Cocina": "En la cocina se encontraba la cocinera un tanto agitada",
        "Patio": "El jardinero estaba en el patio a la hora de lo ocurrido",
        "Cuarto de herramientas": "En el cuarto de herramientas se encontraba la esposa y se logro encontrar un cuchillo que pertenecia a la cocina",
        "Dormitorio": "Se encontro al esposo muerto y con algunas puñaladas",
        "Pildora": "Se encontro una pildora en el dormitorio sin usar",
        "Pistola": "Se encontro una pistola en el dormitorio",
        "Cuchillo": "Se encontro un cuchillo en el cuarto de herramientas",
        "Bat de beisbol": "El bat de beisbol se encontro en la oficina",
        "Machete": "El machete se encontro en el cuarto de herramientas",
        "Cocinera": "No se porque dudan de mi, yo le lleve el cafe al jefe, aunque si me permite decirlo era una mala persona, se lo merecia",
        "Maestro": "Yo no se que fue lo que ocurrio, estaba bebiendo con el y con el genio en la oficina y de repente me quede dormido",
        "Genio": "Yo no se que fue lo que ocurrio, estaba bebiendo con el y con el maestro en la oficina y de repente me quede dormido",
        "Esposa": "Yo no pude ser yo estaba en el cuarto de herramientas aunque cuando sali alcance a ver a una persona corriendo",
        "Jardinero": "yo me encontraba en el patio acomodando las herramientas que utilice en la tarde",
        "ConclusionC": "La verdad fue que la cocinera estaba enamorada del esposo y solo lo quería para ella, pero al saber que él no dejaría a su esposa, algo dentro de ella cambio he ideo el plan maestro",
        "ConclusionL": "A las 11:45 como estaba estipulado la cocinera le llevaría el café de la noche a su oficina donde el esposo se encontraba conversando con el genio acerca de un plan para cambiar el mundo, pero en eso llego el maestro y con una envidia profunda hacia el esposo puesto que el tenia todo lo que el quería los emborracho, de repente todos quedaron totalmente ebrios y la cocinera aprovecho su momento y llevo  al dormitorio al esposo con la intención de tener un bebe con el esposo pero el no se dejo puesto que era amaba demasiado a su esposa, la cocinera no soporto tal rechazo y al saber que la esposa estaba en el cuarto de herramientas y el jardinero estaba en el patio y sus dos amigos estaban totalmente ebrios lo asesino con el cuchillo posterior a eso escondió el cuchillo en el cuarto de herramientas y se dirigió de inmediato a la cocina. al dar las 12 la esposa se dirigió al dormitorio y lo encontró muerto e inmediatamente llamo a todos los que estaban en esa casa y al detective",
        "Resultado_correcto" : ["Cocinera","Cuchillo","Dormitorio"]
    },
    "historia3": {
        "Oficina": "El genio y el maestro estaban en la oficina dormidos y se encontraron algunos vasos con alcohol",
        "Cocina": "En la cocina se encontro al esposo muerto en cuanto llego la cocinera",
        "Patio": "El jardinero estaba en el patio a la hora de lo ocurrido",
        "Cuarto de herramientas": "En el cuarto de herramientas se encontraba la esposa",
        "Dormitorio": "Se encontro la pistola en el dormitorio",
        "Pildora": "Se encontro una pildora en el dormitorio sin usar",
        "Pistola": "Se encontro una pistola en el dormitorio",
        "Cuchillo": "Se encontro un cuchillo en el cuarto de herramientas",
        "Bat de beisbol": "El bat de beisbol se encontro en la oficina",
        "Machete": "El machete se encontro en el cuarto de herramientas",
        "Cocinera": "No se porque dudan de mi, yo le lleve el cafe al jefe, !!!Yo lo amaba!!!",
        "Maestro": "Yo no se que fue lo que ocurrio, estaba totalmente ebrio no se nada",
        "Genio": "Yo no se que fue lo que ocurrio, estaba bebiendo con el y con el maestro en la oficina y de repente me quede dormido",
        "Esposa": "Yo no pude ser yo estaba en el cuarto de herramientas",
        "Jardinero": "Yo me encontraba en el patio acomodando las herramientas que utilice en la tarde",
        "ConclusionC": "La verdad fue que el maestro tenia envidia del éxito del esposo y no podía vivir con el éxito de su compañero así que decidió asesinarlo",
        "ConclusionL": "A las 11:45 como estaba estipulado la cocinera le llevaría el café de la noche a su oficina donde el esposo se encontraba conversando con el genio acerca de un plan para cambiar el mundo, pero en eso llego el maestro y con una envidia profunda hacia el esposo puesto que el tenía todo lo que él quería los emborracho, de repente todos quedaron totalmente ebrios a excepción del maestro y la cocinera aprovecho su momento, lo llevo al dormitorio con la intención de tener un bebe con el esposo pero él no se dejó puesto que era homosexual, la cocinera no soporto tal rechazo y se fue llorando al patio, el maestro al ver tal acto amenazo a la esposo de decirle toda la verdad a la esposa y se encamino al cuarto de herramientas donde se encontraba la esposa, al saber esto el esposo salió corriendo y lo detuvo en la cocina en donde lo intento frenar pero al hacer esto, el maestro poseído por la furia y la envidia agarro un bat de beisbol lo golpeo en la cabeza causando su muerte, el maestro sabia que el  jardinero estaba en el patio y la cocinera no tardaría en llegar a la cocina hacía que decidió aventar el bat en el dormitorio que quedaba enfrente de la oficina  y empezó a tomar todo el alcohol que quedaba para asimilar que estaba extremadamente ebrio y se acostó en el suelo con el genio. al dar las 12 la cocinera llego a la cocina y lo encontró muerto e inmediatamente llamo a todos los que estaban en esa casa y al detective",
        "Resultado_correcto" : ["Maestro","Bat de beisbol","Cocina"]
    },
    "historia4": {
        "Oficina": "El genio y el maestro estaban en la oficina dormidos y se encontraron algunos vasos con alcohol",
        "Cocina": "En la cocina se encontraban la cocinera",
        "Patio": "El jardinero estaba en el cuarto de herramientas con la esposa",
        "Cuarto de herramientas": "En el cuarto de herramientas se encontraba la esposa",
        "Dormitorio": "Se encontro la pildora en el dormitorio",
        "Pildora": "Se encontro una pildora en el dormitorio sin usar",
        "Pistola": "Se encontro una pistola en el cuarto de herramientas con una bala que faltaba",
        "Cuchillo": "Se encontro un cuchillo en la cocina",
        "Bat de beisbol": "El bat de beisbol se encontro en la oficina",
        "Machete": "El machete se encontro en el cuarto de herramientas",
        "Cocinera": "No se porque dudan de mi, yo le lleve el cafe al jefe, !!!Yo lo amaba!!!",
        "Maestro": "Yo no se que fue lo que ocurrio, estaba bebiendo con el y con el genio en la oficina y de repente me quede dormido",
        "Genio": "Yo no se que fue lo que ocurrio, estaba bebiendo con el y con el maestro en la oficina y de repente me quede dormido",
        "Esposa": "Yo no pude ser yo estaba en la oficina",
        "Jardinero": "Yo no pude ser yo estaba en la cocina",
        "ConclusionC": "la verdad fue que la esposa lo mato puesto que la encontró el esposo teniendo relaciones con el jardinera y se comenzó una discusión que no se pudo controlar",
        "ConclusionL": "A las 11:45 como estaba estipulado la cocinera le llevaría el café de la noche a su oficina donde el esposo se encontraba conversando con el genio acerca de un plan para cambiar el mundo, pero en eso llego el maestro y con una envidia profunda hacia el esposo puesto que el tenía todo lo que él quería los emborracho, de repente todos quedaron totalmente ebrios y la cocinera aprovecho su momento y lo llevo al dormitorio con la intención de tener un bebe con el esposo pero él no se dejó puesto que era homosexual, la cocinera no soporto tal rechazo y se fue llorando al patio, el esposo arrepentido de la situación por la que pasaba se dirigió con la esposa al cuarto de herramientas donde esta tenía relaciones con el jardinero, el esposo sorprendido inicio una discusión y amenazo a la esposa de dejarla sin nada, la esposa sin saber que hacer agarro la pistola que se encontraba en el cuarto de herramientas y lo asesino, el jardinero sorprendido fue manipulado por la esposa para esconder el arma en el dormitorio y después se  encamino a la cocina donde se encontraba la cocinera, al dar las 12 la esposa inmediatamente llamo a todos los que estaban en esa casa y al detective",
        "Resultado_correcto" : ["Esposa","Pistola","Cuarto de herramientas"]
    },
    "historia5": {
        "Oficina": "Se encontro el cuerpo del esposo",
        "Cocina": "En la cocina se encontraron restos del café que la cocinera prepaba",
        "Patio": "El jardinero no ha terminado su trabajo, a pesar de que ya terminó su turno",
        "Cuarto de herramientas": "En el cuarto de herramientas se encontraba la esposa",
        "Dormitorio": "Se encontro la pistola en el dormitorio",
        "Pildora": "Se encontro una pildora en el dormitorio sin usar",
        "Pistola": "Se encontro una pistola en el dormitorio",
        "Cuchillo": "Se encontro un cuchillo ensangrentado en el patio",
        "Bat de beisbol": "El bat de beisbol se encontro en la oficina",
        "Machete": "El machete se encontro en el cuarto de herramientas",
        "Cocinera": "No se porque dudan de mi, yo le lleve el cafe al jefe, !!!Yo lo amaba!!!",
        "Maestro": "Yo no se que fue lo que ocurrio, debido al alcohol me quede dormido",
        "Genio": "Yo no se que fue lo que ocurrio, estaba bebiendo con el y con el maestro en la oficina y de repente me quede dormido",
        "Esposa": "Yo no pude ser yo estaba en el cuarto de herramientas, acababa de discutir con el",
        "Jardinero": "Se me hizo un poco tarde pero yo siempre estuve haciendo mi trabajo",
        "ConclusionC": "La verdad fue que el jardinero mató al esposo con un cuchillo porque este lo sorprendió robando su dinero",
        "ConclusionL": "A las 11:45 como estaba estipulado la cocinera le llevaría el café de la noche a su oficina donde el esposo se encontraba conversando con el genio acerca de un plan para cambiar el mundo, entonces en este momento el jardinero, el cual era el trabajador nuevo, decidió que era el momento perfecto para robar todos los ahorros con los cuales el esposo llevaría a cabo su plan, eran los ahorros de toda su vida, por lo cual, no era una suma nada modesta.El  maestro se reunió  y con ellos, debido a su pasado él sentía una envidia profunda hacia el esposo puesto que él tenía todo lo que él quería los emborrachó, de repente todos quedaron totalmente ebrios y la cocinera aprovechó su momento y llevó  al dormitorio al esposo con la intención de tener un bebe con el esposo. La esposa notó algo raro al no encontrar a su esposa y fue al dormitorio, viendo lo que estaban haciendo su esposo y la cocinera  se enojó y comenzó una discusión con el esposo así que la cocinera se fue inmediatamente hacia la cocina, la esposa al saber que tenia visitas evito seguir peleando y se fue corriendo al cuarto de herramientas y se puso a llorar, el esposo fue a la oficina para seguir con el trato.Mientras todo esto sucedía el jardinero aprovecho para robar el dinero del esposo. Tanto el genio como el maestro seguían dormidos por tanto alcohol, entonces mientras el jardinero llevaba a cabo su atraco en la oficina fue sorprendido por el esposo, el cual al percatarse de esto, sin pensarlo sacó su cuchillo y apuñaló al esposo hasta que este quedó inmovil, entonces el fue al patio a seguir con su trabajo, como si nada hubiera pasado. Al dar las 12 la esposa se dirigió al dormitorio para una explicación más clara y lo encontró muerto en la oficina, inmediatamente llamo a todos los que estaban en esa casa y al detective",
        "Resultado_correcto" : ["Jardinero","Cuchillo","Oficina"]
    },
    "historia6": {
        "Oficina": "Se encontro el cuerpo del esposo",
        "Cocina": "Se encontró el cuerpo del esposo cortado en pedazos",
        "Patio": "El jardinero estaba trabajando en el patio a la hora de lo ocurrido",
        "Cuarto de herramientas": "En el cuarto de herramientas se encontraba la esposa",
        "Dormitorio": "Se encontró sangre en el dormitorio, ropa del esposo y ropa de mujer",
        "Pildora": "Se encontro una pildora en el dormitorio sin usar",
        "Pistola": "Se encontro una pistola en el dormitorio",
        "Cuchillo": "Se encontro un cuchillo en el cuarto de herramientas",
        "Bat de beisbol": "El bat de beisbol se encontro en la oficina",
        "Machete": "El machete se encontro en la cocina está manchado de sangre, siempre está en el dormitorio",
        "Cocinera": "Yo estaba dejando el café en la oficina y antes ayudando al jardinero",
        "Maestro": "Yo no se que fue lo que ocurrio, debido al alcohol me quede dormido",
        "Genio": "Yo no se que fue lo que ocurrio, estaba bebiendo con el y con el maestro en la oficina y de repente me quede dormido",
        "Esposa": "Yo no pude ser yo estaba en el cuarto de herramientas, acababa de discutir con el",
        "Jardinero": "Estaba trabajando en el patio",
        "ConclusionC": "La verdad fue que la cocinera pertenecía a una secta caníbal, así que mató al esposo con un machete para después comerlo.",
        "ConclusionL": "a las 11:45 como estaba estipulado la cocinera le llevaría el café de la noche a su oficina donde el esposo se encontraba conversando con el genio acerca de un plan para cambiar el mundo. En eso llegó el maestro y con una envidia profunda hacia el esposo puesto que el tenia todo lo que él quería los emborrachó, de repente todos quedaron totalmente ebrios y la cocinera aprovechó su momento y lo llevó al dormitorio, haciéndole creer que estaba enamorada de él y que quería tener un bebé. El esposo le creyó y decidió engañar a su esposa, la cual se encontraba se encontraba en el cuarto de herramientas, y la cocinera al saber que tanto el genio como el maestro se encontraban dormidos en la oficina debido al alcohol y el jardinero se encontraba trabajando en el patio, la cocinera asesinó al esposo sin piedad  en el dormitorio con el machete que utilizaba para hacer sus deliciosos cortes después  lo llevó a la cocina para comerse al esposo. Después la cocinera se fue a la oficina para fingir que llevaba más café a las personas que estaban haciendo un trato, mientras ella estaba en la oficina, haciendo como si no pasara nada, la esposa fue al dormitorio para descansar y encontró  los restos de sangre, así que los siguió y encontró el cuerpo inerte de su esposo en  la cocina, por lo cual inmediatamente llamo a todos los que estaban en esa casa y al detective.",
        "Resultado_correcto" : ["Cocinera","Machete","Dormitorio"]
    },
    "historia7": {
        "Oficina": "Se encontro el cuerpo del esposo, hay 3 vasos, 2 vacios y uno lleno de alcohol",
        "Cocina": "Se encontró agua caliente con la que se preparó el café, y lagrimas en el suelo ",
        "Patio": "El jardinero estaba trabajando en el patio a la hora de lo ocurrido",
        "Cuarto de herramientas": "En el cuarto de herramientas se encontraba la esposa",
        "Dormitorio": "Se encontró ropa del esposo y de alguna mujer",
        "Pildora": "Se encontro una pildora en el dormitorio sin usar",
        "Pistola": "Se encontro una pistola en la oficina, hace falta una bala en el cargador",
        "Cuchillo": "Se encontro un cuchillo en el cuarto de herramientas",
        "Bat de beisbol": "El bat de beisbol se encontro en la oficina",
        "Machete": "El machete se encontro en el cuarto de herramientas",
        "Cocinera": "No se porque dudan de mi, yo le lleve el cafe al jefe, !!!Yo lo amaba!!!",
        "Maestro": "Yo no se que fue lo que ocurrio, debido al alcohol me quede dormido y no recuerdo nada",
        "Genio": "Yo no fui, -Dice el genio, muy seriamente ",
        "Esposa": "Yo no pude ser yo estaba en el cuarto de herramientas y cuando me encamine a la oficina lo encontre muerto y posterior a eso lo llame",
        "Jardinero": "Estaba trabajando en el patio",
        "ConclusionC": "El Genio mató al esposo a pesar de que eran amigos, porque el genio trabajaba para el gobierno, que era competencia a la del esposo.",
        "ConclusionL": "a las 11:45 como estaba estipulado la cocinera le llevaría el café de la noche a su oficina donde el esposo se encontraba conversando con el genio acerca de un plan para cambiar el mundo, pero en eso llego el maestro y con una envidia profunda que sentía hacia el esposo puesto que el tenía todo lo que el quería los emborracho, el genio tenía instrucciones de hacer que el plan de el esposo no se llevara a cabo, aprovecho la envidia que sentía el maestro hacía el esposo, intuyo su plan de dejarlo en ridículo y le siguió la corriente, de repente observo que se estaban totalmente ebrios y el midiendo su bebida se hizo el borracho, el genio al ver que ninguno de los dos estaba consciente de lo que pasaba  y viendo las intenciones de la cocinera y al saber que la esposa estaba en el cuarto de herramientas y el jardinero estaba en el patio, e inmediatamente en cuanto la cocinera se llevó al esposo él, la cocinera lo llevo al dormitorio con la intención de tener un bebe con el 	esposo pero él no se dejó puesto que era homosexual, la cocinera no soporto tal rechazo y se fue llorando a la cocina, de repente regreso el esposo a la oficina donde se encontraban el genio y el maestro este ultimo dormido, por lo cual al verlo lo mató con la pistola de un disparo a la cabeza y acomodó todo de tal manera que pareciera un suicidio, después el genio fingió estar inconciente esperando a que alguien encontrará el cuerpo, a las 12 la esposa se dirigió a la oficina y lo encontró muerto e inmediatamente llamo a todos los que estaban en esa casa y al detective.",
        "Resultado_correcto" : ["Genio","Pistola","Oficina"]  
    },
    "historia8": {
        "Oficina": "El genio y el maestro estaban en la oficina dormidos y se encontraron algunos vasos con alcohol",
        "Cocina": "Se encontró agua caliente con la que se preparó el café ",
        "Patio": "El cuerpo del esposo está tirado en el pasto",
        "Cuarto de herramientas": "En el cuarto de herramientas se encontraba la esposa y el jardinero",
        "Dormitorio": "Se encontró ropa del esposo y de alguna mujer",
        "Pildora": "Se encontro una pildora en el dormitorio sin usar",
        "Pistola": "Se encontro una pistola en la oficina",
        "Cuchillo": "Se encontro un cuchillo en el cuarto de herramientas",
        "Bat de beisbol": "El bat de beisbol se encontro lleno de sangre en el patio, se sabe que es del jardinero y lo utiliza los fines de semana",
        "Machete": "El machete se encontro en el cuarto de herramientas",
        "Cocinera": "No se porque dudan de mi, yo le lleve el cafe al jefe, !!!Yo lo amaba!!!",
        "Maestro": "Yo no se que fue lo que ocurrio, debido al alcohol me quede dormido y no recuerdo nada",
        "Genio": "Yo no fui, -Dice el genio, muy seriamente ",
        "Esposa": "Yo no pude ser yo estaba en el cuarto de herramientas y cuando me encamine a la oficina lo encontre muerto y posterior a eso lo llame",
        "Jardinero": "Estaba hablando con la esposa acerca de la discusión",
        "ConclusionC": "la verdad fue que el jardinero estaba enfadado del esposo por los maltratos constantes hacia su persona ",
        "ConclusionL": "a las 11:45 como estaba estipulado la cocinera le llevaría el café de la noche a su oficina donde el esposo se encontraba conversando con el genio acerca de un plan para cambiar el mundo, pero en eso llego el maestro y con una envidia profunda hacia el esposo puesto que él tenía todo lo que él quería los emborrachó, de repente todos quedaron totalmente ebrios y la cocinera aprovechó su momento y llevó  al dormitorio al esposo con la intención de tener un bebe con el esposo, pero de repente la esposa llegó al dormitorio y viendo lo que estaban haciendo su esposo y la cocinera  se enojó y comenzó una discusión con el esposo así que la cocinera se fue inmediatamente hacia la cocina, la esposa al saber que tenia visitas evito seguir peleando y se fue corriendo al cuarto de dormitorio, cerró la puerta debido a que estaba muy molesta, el esposo después de un momento intentó hablar con ella, pero lo ignoró entonces al salir al patio, vio al jardinero descansando, a pesar de que llevaba toda la tarde trabajando sin descanso y sin alimento, el esposo al estar molesto decidió desquitarse de el, por lo que empezó a agredirlo, diciendo que se la pasaba todo el día descansando, lo cual no era cierto. El jardinero que estaba harto de esos abusos, por lo que agarró el bate que tenía al lado y lo mató a golpes, al saber que la esposa estaba en el dormitorio y tanto el genio como el maestro totalmente ebrios,  lo asesnó y lo dejo en el pasto, se dirigió de inmediato al cuarto de herramientas a consolar a la esposa. al dar las 12 la esposa se dirigió al dormitorio para una explicación más clara y lo encontró muerto en el patio, inmediatamente llamo a todos los que estaban en esa casa y al detective",
        "Resultado_correcto" : ["Jardinero","Bat de beisol","Patio"]  
    },
    "historia9": {
        "Oficina": "El genio y el esposo estaban en la oficina platicando de sus nuevos inventos",
        "Cocina": "En la cocina se encontraba la concinera preparando el desayuno como cada dia",
        "Patio": "El Genio se encontraba en el patio revisando el carro de la esposa a la hora de lo ocurrido",
        "Cuarto de herramientas": "El cuarto de herramientas se encontraba el maestro buscando su material didactico pues no lo encontraba en la casa",
        "Dormitorio": "En el dormitorio se econtraba la esposa planeando como hacer el asesinato",
        "Pildora": "Se encontro una pildora rota en la basura de la cocina",
        "Pistola": "Se encontro una pistola en el dormitorio",
        "Cuchillo": "Se encontraron los cuchillos en la cocina",
        "Bat de beisbol": "El bat de beisbol se encontro en la oficina como adorno",
        "Machete": "El machete se encontro en el jardin",
        "Cocinera": "No se porque dudan de mi, yo le lleve el cafe al jefe a las 11:45pm ademas que yo estaba haciedno el desayuno como todos los dias, ¡¡¡Jamas le haria eso!!!",
        "Maestro": "Yo no se que fue lo que ocurrio, estaba buscando mi material para dar la clase al hijo, deberias preguntarle al genio",
        "Genio": "Yo no recuerdo que fue lo que sucedio, estaba arreglando el carro cuando escuche un ruido regrese a la oficina y lo encontre tirado pero no se que paso",
        "Esposa": "Yo no pude ser yo estaba en el cuarto y solo baje para pedirle al Genio que checara mi coche",
        "Jardinero": "yo me encontraba en el patio podando los arboles de la casa",
        "ConclusionC": "La verdad fue que la Esposa mató al esposo porque estaba enojada pues no le compro su regalo de aniversario que tanto quería.",
        "ConclusionL": "A las 11:45 como estaba estipulado la cocinera le llevaría el café de la noche a su oficina donde el esposo se encontraba conversando con el genio acerca de un plan para cambiar el mundo, entonces en este momento la Esposa  entró a la oficina y le dijo al Genio que necesitaba ayuda para arreglar su coche pues no prende, mientras el Genio salió a revisar el carro de la esposa y el  Esposo estaba en la oficina, la Esposa tomó el bat de beisbol que lo tenia de adorno en su oficina y lo mató huyendo inmediatamente del lugar del crimen. Regresó el Genio a la oficina y vio el cuerpo del esposo tirado con la cara destrozada , inmediatamente llamó a todos los que estaban en esa casa y al detective.",
        "Resultado_correcto" : ["Esposo","Bat de beisol","Oficina"] 
    },
    "historia10": {
        "Oficina": "El genio y el esposo estaban en la oficina platicando de sus nuevos inventos",
        "Cocina": "En la cocina se encontraba la cocinera un tanto agitada",
        "Patio": "El jardinero estaba en el patio a la hora de lo ocurrido",
        "Cuarto de herramientas": "En el cuarto de herramientas no se encontraba nadie",
        "Dormitorio": "Se encontraba la esposa con sus hijos",
        "Pildora": "Se encontro una pildora en el dormitorio sin usar",
        "Pistola": "Se encontro una pistola en el cuarto de herramientas",
        "Cuchillo": "Se encontro un cuchillo en el dormitorio",
        "Bat de beisbol": "El bat de beisbol se encontro en la oficina",
        "Machete": "El machete se encontro en el patio",
        "Cocinera": "No se porque dudan de mi, yo le lleve el cafe al jefe y fui quien lo vio tirado y avise rapidamente, aunque si me permite decirlo era una mala persona, se lo merecia",
        "Maestro": "Yo no se que fue lo que ocurrio, estaba bebiendo con el y con el genio en la oficina",
        "Genio": "Yo no se que fue lo que ocurrio, estaba bebiendo con el y con el maestro en la oficina",
        "Esposa": "Yo no pude ser yo estaba en el dormitorio con mis hijos aunque sali y alcance a ver a una persona corriendo",
        "Jardinero": "yo me encontraba en el patio acomodando las herramientas que utilice en la tarde",
        "ConclusionC": "La verdad fue que el Genio mató al esposo porque quería quedarse con todas las regalías del invento.",
        "ConclusionL": "A las 11:45 como estaba estipulado la cocinera le llevaría el café de la noche a su oficina donde el esposo se encontraba conversando con el genio y el maestro acerca de un plan para cambiar el mundo, entonces en este momento su esposa le habló que si podía ir al cuarto pues le tenía que decir algo importante de sus hijos, mientras el esposo iba a ver lo que ocupaba la esposa el Genio aprovecho para ir al cuarto de herramientas y tomar la pistola, cuando el Genio iba regresando a la oficina se encontró con el esposo en la cocina y fue el momento perfecto para matarlo pues nadie sospecharía porque rápidamente regresó a la oficina como si nunca hubiera salido de ahí, hasta que la cocinera lo encontró tirado en la cocina he inmediatamente llamó a todos los que estaban en esa casa y al detective.",
        "Resultado_correcto" : ["Genio","Pistola","Cocina"] 
    },
    "historia11": {
        "Oficina": "El genio y el esposo estaban en la oficina platicando de sus nuevos inventos",
        "Cocina": "En la cocina se encontraba el jardinero tomando un vaso de agua",
        "Patio": "El patio se encontraba solo pues no habia nada que arreglar ese dia",
        "Cuarto de herramientas": "En el cuarto de herramientas se encontraba la esposa buscando un foco para su lampara",
        "Dormitorio": "Se encontraba la cocinera recogiendo el desayuno que les llevo a la cama",
        "Pildora": "Se encontro una pildora en el dormitorio sin usar",
        "Pistola": "Se encontro una pistola en la oficina",
        "Cuchillo": "Se encontro un cuchillo en el cuarto de herramientas",
        "Bat de beisbol": "El bat de beisbol se encontro en la oficina",
        "Machete": "El machete se encontro en el patio tirado en el jardin",
        "Cocinera": "No se porque dudan de mi, yo le lleve el cafe al jefe y estaba recogiendo su desayuno en la cama, !!!Yo lo amaba!!!",
        "Maestro": "Yo no se que fue lo que ocurrio, estaba dando clases su hijo pero me ocurrio un percance y me tuve que ir pronto",
        "Genio": "Yo no se que fue lo que ocurrio, estaba bebiendo con el y fue a un mandado pero ya no volvio",
        "Esposa": "Yo no pude ser yo estaba en el cuarto de herramientas",
        "Jardinero": "Yo me encontraba en la cocina tomando un vaso de agua y descansando",
        "ConclusionC": "La verdad fue que el Maestro mató al esposo porque quería quedarse con su esposa pues ya mantenían una relación de años pero la esposa no se animaba a dejar al esposo. ",
        "ConclusionL": "A las 11:45 como estaba estipulado la cocinera le llevaría el café de la noche a su oficina donde el esposo se encontraba conversando con el genio acerca de un plan para cambiar el mundo, el maestro llegó como cada día a darle clases al hijo más chico del esposo, pasó su hora de clase y le dijo al niño que le dijera a su papá si podía salir al patio a pagarle lo de la clase, salió el esposo a pagarle pero discutieron del tiempo y la calidad de las clases que el maestro impartía, eso hizo enojar al maestro juntándose con el enojo que tenia por no poder estar con su esposa, volteo al jardín del patio donde se encontraba un machete y sin pensarlo tomó el machete y lo degolló huyendo rápido del lugar del delito, hasta que el jardinero  lo encontró tirado en el patio he inmediatamente llamó a todos los que estaban en esa casa y al detective.",
        "Resultado_correcto" : ["Maestro","Patio","Machete"]
    },
    "historia12": {
        "Oficina": "El genio y el maestro se encontraban en la oficina totalmente ebrios ",
        "Cocina": "En la cocina se encontraba los invitados de ese dia",
        "Patio": "El jardinero estaba en el patio a la hora de lo ocurrido",
        "Cuarto de herramientas": "En el cuarto de herramientas se encontraba la esposa enojada por lo que había encontrado",
        "Dormitorio": "Se encontraba el esposo y la cocinera teniendo intimidad",
        "Pildora": "Se encontro una pildora en el dormitorio sin usar",
        "Pistola": "Se encontro una pistola en la oficina",
        "Cuchillo": "Se encontro un cuchillo en el cuarto de herramientas",
        "Bat de beisbol": "El bat de beisbol se encontro en la oficina",
        "Machete": "El machete se encontro en el patio tirado en el jardin",
        "Cocinera": "No se porque dudan de mi, yo le lleve el cafe al jefe y estaba con el en la cama, !!!Yo lo amaba!!!",
        "Maestro": "Yo no se que fue lo que ocurrio, estaba totalmente ebrio con el genio",
        "Genio": "Yo no se que fue lo que ocurrio, estaba bebiendo con maestro y quedamos totalmente ebrios",
        "Esposa": "Yo no pude ser yo estaba en el cuarto de herramientas enojada",
        "Jardinero": "Yo me encontraba en el patio pintando unas paredes",
        "ConclusionC": "la verdad fue que el jardinero estaba celoso del esposo por la mujer que tenía y al verla sufrir por la infidelidad no lo soporto y se dirigió a matarlo ",
        "ConclusionL": "a las 11:45 como estaba estipulado la cocinera le llevaría el café de la noche a su oficina donde el esposo se encontraba conversando con el genio acerca de un plan para cambiar el mundo, pero en eso llego el maestro y con una envidia profunda hacia el esposo puesto que el tenia todo lo que el quería los emborracho, de repente todos quedaron totalmente ebrios y la cocinera aprovecho su momento y llevo  al dormitorio al esposo con la intención de tener un bebe con el esposo, pero de repente la esposa llego al dormitorio y viendo lo que estaban haciendo su esposo y la cocinera  se enojó y comenzó una discusión con el esposo así que la cocinera se fue inmediatamente hacia la cocina, la esposa al saber que tenia visitas evito seguir peleando y se fue corriendo al cuarto de herramientas, el esposo después de un momento intento llegar a ella pero el jardinero lleno de celos lo freno en el patio, al saber que la esposa estaba en el cuarto de herramientas y  sus dos amigos estaban totalmente ebrios,  lo asesino con el machete y posterior a eso lo limpio y lo dejo en el pasto, se dirigió de inmediato al cuarto de herramientas a consolar a la esposa. al dar las 12 la esposa se dirigió al dormitorio para una explicación mas clara y lo encontró muerto en el patio, inmediatamente llamo a todos los que estaban en esa casa y al detective",
        "Resultado_correcto" : ["Jardinero","Machete","Patio"]
    }
}

histNumber = randint(1, 12)


def editHistNumber():
    global histNumber
    while True:
        newData = randint(1, 12)
        if(newData != histNumber):
            histNumber = newData
            break


tipoCosas = {
    "Personas": ["Cocinera", "Maestro", "Genio", "Esposa", "Jardinero"],
    "Armas": ["Machete", "Bat de beisbol", "Cuchillo", "Pistola", "Pildora"],
    "Lugares": ["Oficina", "Cocina", "Patio", "Cuarto de herramientas", "Dormitorio"],
}
